# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf81a30f967553582723951e613699412d588f54760368b22ea17fb4d2741f45af0f89d2d0b8811ad8c1838998ff945113e16981c34367c8a0ec10f1ffb04f3

test:
  secret_key_base: 4305b007846ecf0db9b4840ea6d44dba25a78c5af42dac7eb51b5ba7bbdb4243557035bfc4388eb86e2865001095d2520df0c141feec8d730bb37c385e8d1d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
